apiVersion: apps/v1
kind: Deployment
metadata:
  name: airquality-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airquality-api
  template:
    metadata:
      labels:
        app: airquality-api
    spec:
      containers:
        - name: api
          image: pamelabusiness/airquality-mlops:latest
          ports:
            - containerPort: 5000
