name: CT - Continuous Training

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python src/preprocess.py

      - name: Retrain model
        run: python src/train.py

      - name: Upload retrained model
        uses: actions/upload-artifact@v3
        with:
          name: retrained-model
          path: model/model.pkl
